name: Verify WindowsCare
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  powershell-51:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Test without modifying Windows
        shell: powershell
        run: .\Tests\Run-Tests.ps1
